services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://<render-app-url>
    plan: free
